[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=
Numlock=on
RebootCommand=

[Theme]
Current=01-breeze-fedora
CursorTheme=Vimix-cursors
Font=NotoSans Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1

[Users]
MaximumUid=60000
MinimumUid=1000
