format = """
[](#3B4252)\
$os\
$hostname\
[](bg:#434C5E fg:#3B4252)\
$username\
[](fg:#434C5E bg:#4C566A)\
$directory\
[](fg:#4C566A bg:white)\
$git_branch\
$git_state\
$git_status\
$git_metricsics\
[](fg:white bg:blue)\
$docker_context\
[ ](fg:blue)\
"""

command_timeout = 5000

# A continuation prompt that displays two filled-in arrows
continuation_prompt = '▶▶ '

[os]
style = "bg:#3B4252"
format = "[ $symbol]($style)"
disabled = false

[hostname]
ssh_symbol = "  "
ssh_only = false
style = "bg:#3B4252"
format = '[$ssh_symbol](bold blue bg:#3B4252)[$hostname ](bold red bg:#3B4252)'
disabled = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#434C5E fg:yellow"
style_root = "bg:#434C5E fg:red"
format = "[ $user ]($style)"

[directory]
read_only = "󰌾 "
style = "bg:#4C566A"
format = "[ $path $read_only]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:white fg:black"
format = '[ $symbol $branch ]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ PICKING](bold red)'

[git_status]
style = "bg:white fg:black"
format = '[$all_status$ahead_behind ]($style)'

[git_metrics]
added_style = 'bold green'
deleted_style = 'bold red'
format = '[$added]($added_style)/[$deleted]($deleted_style) '

#Nerd font preset
[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
